json.id user.id
json.first_name user.first_name
json.last_name user.last_name
json.email user.email
json.phone_number user.phone_number
json.bio user.bio
json.avatar_url user.avatar_url
json.location user.location
json.admin user.admin
json.created_at user.created_at